### ISSUE TITLE
Minimum Python version to 3.10 TODO

### ISSUE THREAD

**Issue by maread99** [maread99/market_prices#201]
#### type annotations
- [x] **Use of `Optional` and `Union`** can now be migrated to using the `|` operator in the following circumstances:
  - [x] **parameter annotations of functions decorated with `@valimp.parse`** (get_type_hints did not support the | operator prior to py 3.10). For example, `Optional[Union[str, float, int]]` can now be annotated as `str | float | int | None`.
  - [x] creating **type aliases**, for example `Symbols = Union[list[str], str]` can now be defined as `Symbols = list[str] | str`
  - [x] Indeed, search across the library for any references to `Optional` and `Union`, including with the docs, and remove / revise.
- [x] Should also be able to lose the `from __future__ import annoations` lines from the top of modules.
- [x] Can probably by now revert the [fix](https://github.com/maread99/market_prices/commit/4a3e2dea3594b09d23c6febe087a942954994e6f) implemented to accommodate bug in pandas 2.1.0 concerning treatment of origin. Intention in https://github.com/pandas-dev/pandas/issues/55064 was to revert in 2.1.1. Required changes to revert fix are noted in [comments on the commit](https://github.com/maread99/market_prices/commit/4a3e2dea3594b09d23c6febe087a942954994e6f#r126917721).

**Comment by maread99** [comment]
Would be closed by #353
