### ISSUE TITLE
Minimum python version to 3.9 TODO

### ISSUE THREAD

**Issue by maread99** [maread99/market_prices#9]
TODO for advancing minimum python version to 3.9:

####  `intervals.py`
- [x] ~Look to change following enum class methods to class properties:~
    * ~`_BaseInterval.daily_bi`~
    * ~`_BaseInterval.intraday_bis`~
    EDIT 22/06/07 - no longer an option as from 3.11 wrapping other decorators with `classmethod` decorator will be deprecated.

#### pydantic
- [x] given changes with pydantic v2, migrate to in-house input validation and drop the pydantic dependency

#### types
- [x] Typing classes, of like `Optional`, `Union`, `List` etc can be removed in favour of builtin types and the | operator WITH THE **EXCEPTION of not being able to use the | operator in parameter annotations of functions decorated with `@valimp.parse`** (get_type_hints does not support the | operator until py 3.10 - noted forward to migrate these to | as well when bump min py version to 3.10) (NB everywhere, can still use dict as opposed to Dict, and Union[str, None] as opposed to Optional[str].
  - [ ] Also remove these deprecated type generics from all the doc in favour of builtins and | operator.

#### functools
- [x] Change any use of `@functools.lru_cache(maxsize=None)` to `@functools.cache`

#### timezones
- [x] **Drop `pytz` in favor of `zoneinfo`** standard library ~(either now or later). [Looks likely](https://github.com/pandas-dev/pandas/issues/44823) that pandas 2.0 will switch to `zoneinfo` as its default timezone package. If it looks like pandas 2.0 could be released any time soon then might want to address this now. If it looks still to be a way off then could roll this item forwards (to dedicated issue), although in any event pandas already supports `zoneinfo` and would be better off depending on a stdlib library than a third-party one.~ See https://github.com/gerrymanoim/exchange_calendars/issues/322. Move over at same time as `exchange-calendars`.

**Comment by maread99** [comment]
Closed by #204.
